Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
                  puppet module install leonardothibes-jekyll --force;
                  puppet module install puppetlabs-ruby --force;
                  puppet module install puppetlabs-apt --force;
                  puppet module install puppetlabs-stdlib --force;"
  end
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose --debug"
  end
end